name: Api-Test-Build

on:
   push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      
      - name: Install Newman, HTMLReporter and Slack Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-slackreporter
      
      - name: Run Postman Collection
        env:
          COLLECTION_UID: 34671145-a5997067-e2f3-42fd-af0c-b1a01f384963
          ENVIRONMENT_UID: 34671145-9c5ca044-2513-4b0d-b146-16c5c1e532ec
          API_KEY: PMAK-67585d5c8e3c100001b6cabe-62d370d36ab7562316430f5d40024426ac
        run: |
          newman run https://api.getpostman.com/collections/$COLLECTION_UID?apikey=$API_KEY --enviroment https://api.getpostman.com/environment/$ENVIRONMENT_UID?apikey=$API_KEY
        
      - name: Output the Result Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults